# agents/explainer_agent.py

def explainer_agent(parsed_output, solver_output):
    """
    Converts solver output into student-friendly explanation.
    Purely explanation logic.
    """

    if not solver_output or solver_output.get("status") != "success":
        return {
            "explanation": "Solution could not be generated.",
            "steps": []
        }

    topic = parsed_output.get("topic", "")
    answer = solver_output.get("final_answer", "")

    steps = []

    # ---------------------------------------
    # Algebra
    # ---------------------------------------
    if topic == "algebra":
        steps.append("1️⃣ Identify the type of algebraic expression.")
        steps.append("2️⃣ Apply appropriate algebraic method (factoring / formula).")
        steps.append(f"3️⃣ Solve to obtain: {answer}")

    # ---------------------------------------
    # Calculus
    # ---------------------------------------
    elif topic == "calculus":
        if "Derivative" in answer:
            steps.append("1️⃣ Identify the function.")
            steps.append("2️⃣ Apply differentiation rules.")
            steps.append(f"3️⃣ Final derivative: {answer}")
        elif "Limit" in answer:
            steps.append("1️⃣ Identify limit expression.")
            steps.append("2️⃣ Apply limit laws or standard limits.")
            steps.append(f"3️⃣ Final limit value: {answer}")

    # ---------------------------------------
    # Probability
    # ---------------------------------------
    elif topic == "probability":
        steps.append("1️⃣ Identify total possible outcomes.")
        steps.append("2️⃣ Identify favorable outcomes.")
        steps.append(f"3️⃣ Compute probability: {answer}")

    # ---------------------------------------
    # Linear Algebra
    # ---------------------------------------
    elif topic == "linear_algebra":
        steps.append("1️⃣ Identify matrix or vector structure.")
        steps.append("2️⃣ Apply determinant or linear algebra formula.")
        steps.append(f"3️⃣ Final result: {answer}")

    else:
        steps.append(f"Final Answer: {answer}")

    explanation_text = "Step-by-step explanation generated by Explainer Agent."

    return {
        "explanation": explanation_text,
        "steps": steps
    }